# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import conf_pb2 as conf__pb2


class getMatchRatioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getratio = channel.unary_unary(
                '/com.resumematch.grpc.getMatchRatio/getratio',
                request_serializer=conf__pb2.ResumeRequest.SerializeToString,
                response_deserializer=conf__pb2.ResumeResponse.FromString,
                )


class getMatchRatioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getratio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_getMatchRatioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getratio': grpc.unary_unary_rpc_method_handler(
                    servicer.getratio,
                    request_deserializer=conf__pb2.ResumeRequest.FromString,
                    response_serializer=conf__pb2.ResumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.resumematch.grpc.getMatchRatio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class getMatchRatio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getratio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.resumematch.grpc.getMatchRatio/getratio',
            conf__pb2.ResumeRequest.SerializeToString,
            conf__pb2.ResumeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
